/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Deck Events */
        get: operations["streamDeckEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decks */
        get: operations["listDecks"];
        put?: never;
        /** Create */
        post: operations["createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["getDeck"];
        put?: never;
        post?: never;
        /** Delete Deck */
        delete: operations["deleteDeck"];
        options?: never;
        head?: never;
        /** Update Deck */
        patch: operations["updateDeck"];
        trace?: never;
    };
    "/decks/{deck_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: operations["reorderImageSlides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/slides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Slides */
        get: operations["listSlides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/slides/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slide */
        get: operations["getSlide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/slides/{number}/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Hint */
        put: operations["setSlideHint"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Estimate */
        get: operations["getEstimate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Research */
        post: operations["startResearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listDeckSources"];
        put?: never;
        /** Add Source */
        post: operations["addDeckSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["updateDeckSource"];
        trace?: never;
    };
    "/decks/{deck_id}/sources/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approveSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/disagreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disagreements */
        get: operations["listDisagreements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["listDocuments"];
        put?: never;
        /** Create Document */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/download/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["askQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/qa/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["getQaThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Quiz */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quiz_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answerQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quiz_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal */
        post: operations["revealQuizAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerIn */
        AnswerIn: {
            /** Answer */
            answer: string;
        };
        /** Body_addDeckSource */
        Body_addDeckSource: {
            /** File */
            file?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Topic Ids
             * @description JSON list of topic ids
             */
            topic_ids?: string | null;
        };
        /** Body_createDeck */
        Body_createDeck: {
            /**
             * Files
             * @description One PPTX or PDF, or 1–300 images
             */
            files: string[];
            /**
             * Context
             * @description JSON-encoded DeckContext
             */
            context?: string | null;
        };
        /** ClarityCounts */
        ClarityCounts: {
            /**
             * Clear
             * @default 0
             */
            clear: number;
            /**
             * Vague
             * @default 0
             */
            vague: number;
            /**
             * Unreadable
             * @default 0
             */
            unreadable: number;
            /**
             * Divider
             * @default 0
             */
            divider: number;
        };
        /** DeckContext */
        DeckContext: {
            /** Course */
            course?: string | null;
            /** Level */
            level?: ("intro" | "intermediate" | "advanced" | "graduate") | null;
            /** Topic */
            topic?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** DeckDetail */
        DeckDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * File Kind
             * @enum {string}
             */
            file_kind: "pptx" | "pdf" | "images";
            /** Slide Count */
            slide_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "extracting" | "awaiting_input" | "ready_for_research" | "awaiting_research_confirm" | "researching" | "awaiting_source_approval" | "processing_sources" | "ready" | "generating" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            context: components["schemas"]["DeckContext"];
            clarity_counts: components["schemas"]["ClarityCounts"];
            /** Needs Input Count */
            needs_input_count: number;
            active_run?: components["schemas"]["Run"] | null;
            /** Cost Usd */
            cost_usd: number;
            error?: components["schemas"]["Problem"] | null;
        };
        /** DeckSource */
        DeckSource: {
            source: components["schemas"]["Source"];
            /** Topic Ids */
            topic_ids: string[];
            /** Relevance */
            relevance: number;
            /** Authority */
            authority: number;
            /** Reason */
            reason: string;
            /**
             * Added By
             * @enum {string}
             */
            added_by: "research" | "learner";
            /** Approved */
            approved: boolean;
        };
        /** DeckSummary */
        DeckSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * File Kind
             * @enum {string}
             */
            file_kind: "pptx" | "pdf" | "images";
            /** Slide Count */
            slide_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "extracting" | "awaiting_input" | "ready_for_research" | "awaiting_research_confirm" | "researching" | "awaiting_source_approval" | "processing_sources" | "ready" | "generating" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DeckUpdate */
        DeckUpdate: {
            /** Title */
            title?: string | null;
            context?: components["schemas"]["DeckContext"] | null;
        };
        /** Disagreement */
        Disagreement: {
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string;
            /** Claim */
            claim: string;
            /** Involves Slide */
            involves_slide?: number | null;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Assessment */
            assessment: string;
        };
        /** DocStats */
        DocStats: {
            /**
             * Sections
             * @default 0
             */
            sections: number;
            /**
             * Reconstructed Slides
             * @default 0
             */
            reconstructed_slides: number;
            /**
             * Disagreements Shown
             * @default 0
             */
            disagreements_shown: number;
            /**
             * Dropped Blocks
             * @default 0
             */
            dropped_blocks: number;
        };
        /** DocumentIn */
        DocumentIn: {
            /**
             * Organization
             * @enum {string}
             */
            organization: "by_slide" | "by_topic";
            /** Formats */
            formats: ("pdf" | "docx" | "md" | "html")[];
            /** Slide Range */
            slide_range?: number[] | null;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "slide" | "book" | "web";
            /** Label */
            label: string;
            /** Slide */
            slide?: number | null;
            /** Source Id */
            source_id?: string | null;
            /** Page Label */
            page_label?: string | null;
            /** Section Id */
            section_id?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ExplanationDocument */
        ExplanationDocument: {
            /** Id */
            id: string;
            /** Deck Id */
            deck_id: string;
            /**
             * Organization
             * @enum {string}
             */
            organization: "by_slide" | "by_topic";
            /** Formats */
            formats: ("pdf" | "docx" | "md" | "html")[];
            /** Slide Range */
            slide_range?: number[] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "generating" | "rendering" | "ready" | "failed";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Downloads */
            downloads?: {
                [key: string]: string;
            };
            stats?: components["schemas"]["DocStats"];
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error?: components["schemas"]["Problem"] | null;
        };
        /** FormulaOut */
        FormulaOut: {
            /** Latex */
            latex: string;
            /**
             * Unreadable
             * @default false
             */
            unreadable: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Api Key Configured */
            api_key_configured: boolean;
            /**
             * Ocr Path
             * @enum {string}
             */
            ocr_path: "local_gpu" | "provider";
            /** Gpu Name */
            gpu_name?: string | null;
            /** Libreoffice */
            libreoffice: boolean;
            /** Renderer */
            renderer: boolean;
            /** Models */
            models: {
                [key: string]: string;
            };
        };
        /** HintIn */
        HintIn: {
            /** Hint */
            hint: string;
        };
        /** Interpretation */
        Interpretation: {
            /** Meaning */
            meaning: string;
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale: string;
        };
        /** OrderIn */
        OrderIn: {
            /** Order */
            order: number[];
        };
        /** PositionOut */
        PositionOut: {
            /** Statement */
            statement: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
        };
        /** Problem */
        Problem: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
            /**
             * Code
             * @enum {string}
             */
            code: "unsupported_file" | "corrupt_file" | "too_many_slides" | "file_too_large" | "not_found" | "invalid_state" | "api_key_missing" | "api_key_invalid" | "model_not_allowed" | "provider_unavailable" | "rate_limited" | "search_unavailable" | "source_unavailable" | "libreoffice_missing" | "renderer_missing" | "validation_error" | "internal_error";
        };
        /** QaThreadOut */
        QaThreadOut: {
            /** Id */
            id: string;
            /** Turns */
            turns: components["schemas"]["QaTurn"][];
        };
        /** QaTurn */
        QaTurn: {
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "learner" | "assistant";
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["EvidenceRef"][];
            /** Declined */
            declined: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuestionIn */
        QuestionIn: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /** QuizFeedback */
        QuizFeedback: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "correct" | "partial" | "incorrect" | "revealed";
            /** Misconception */
            misconception?: string | null;
            /** Hint */
            hint?: string | null;
            pointer?: components["schemas"]["EvidenceRef"] | null;
            /** Revealed Answer */
            revealed_answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Citations */
            citations?: components["schemas"]["EvidenceRef"][];
            /** Hint Level */
            hint_level: number;
            state: components["schemas"]["QuizState"];
        };
        /** QuizIn */
        QuizIn: {
            /** Slide From */
            slide_from: number;
            /** Slide To */
            slide_to: number;
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** QuizScore */
        QuizScore: {
            /**
             * Correct
             * @default 0
             */
            correct: number;
            /**
             * Answered
             * @default 0
             */
            answered: number;
        };
        /** QuizState */
        QuizState: {
            /** Id */
            id: string;
            /** Deck Id */
            deck_id: string;
            /** Slide From */
            slide_from: number;
            /** Slide To */
            slide_to: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
            /** Index */
            index: number;
            /** Total */
            total: number;
            /** Question */
            question?: string | null;
            /** Hint Level */
            hint_level: number;
            score: components["schemas"]["QuizScore"];
        };
        /** ResearchIn */
        ResearchIn: {
            /**
             * Confirm
             * @constant
             */
            confirm: true;
            /** Topic Ids */
            topic_ids?: string[] | null;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Deck Id */
            deck_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "extract" | "research" | "process_sources" | "generate" | "qa";
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "completed" | "failed" | "cancelled";
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            estimate?: components["schemas"]["RunEstimate"] | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Cost By Stage */
            cost_by_stage?: {
                [key: string]: number;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            error?: components["schemas"]["Problem"] | null;
        };
        /** RunEstimate */
        RunEstimate: {
            /** Stages */
            stages: components["schemas"]["StageEstimate"][];
            /** Total Usd */
            total_usd: number;
            /** Est Minutes */
            est_minutes: number;
            budget?: components["schemas"]["RunEstimateBudget"] | null;
        };
        /** RunEstimateBudget */
        RunEstimateBudget: {
            /** Topics */
            topics: number;
            /** Searches Per Topic */
            searches_per_topic: number;
            /** Pages Per Topic */
            pages_per_topic: number;
        };
        /** Slide */
        Slide: {
            /** Number */
            number: number;
            /** Image Url */
            image_url: string;
            /** Title */
            title?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Formulas */
            formulas?: components["schemas"]["FormulaOut"][];
            /** Visuals */
            visuals?: components["schemas"]["Visual"][];
            /** Topic */
            topic?: string | null;
            /** Concepts */
            concepts?: string[];
            /**
             * Clarity
             * @enum {string}
             */
            clarity: "pending" | "clear" | "vague" | "unreadable" | "divider";
            interpretation?: components["schemas"]["Interpretation"] | null;
            /** Needs Input */
            needs_input: boolean;
            /** Learner Hint */
            learner_hint?: string | null;
            /** Unreadable Regions */
            unreadable_regions?: string[];
            /**
             * Ocr Path
             * @enum {string}
             */
            ocr_path: "native" | "local_ocr" | "provider_vision";
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Origin */
            origin: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[];
            /** Publisher */
            publisher?: string | null;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Isbn */
            isbn?: string | null;
            /**
             * Access
             * @enum {string}
             */
            access: "usable" | "further_reading" | "blocked";
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Processing Status */
            processing_status: string;
            /** Page Count */
            page_count?: number | null;
        };
        /** SourceList */
        SourceList: {
            /** By Topic */
            by_topic: components["schemas"]["TopicSources"][];
            /** Further Reading */
            further_reading: components["schemas"]["Source"][];
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Approved */
            approved: boolean;
        };
        /** StageEstimate */
        StageEstimate: {
            /** Stage */
            stage: string;
            /** Model */
            model: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /** Usd */
            usd: number;
            /**
             * Path
             * @default provider
             * @enum {string}
             */
            path: "provider" | "local";
        };
        /** Topic */
        Topic: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slide Numbers */
            slide_numbers: number[];
            /**
             * Research Status
             * @enum {string}
             */
            research_status: "pending" | "searching" | "done" | "no_reliable_source";
        };
        /** TopicSources */
        TopicSources: {
            topic: components["schemas"]["Topic"];
            /** Sources */
            sources: components["schemas"]["DeckSource"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Visual */
        Visual: {
            /** Id */
            id: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "slide" | "book";
            /**
             * Kind
             * @enum {string}
             */
            kind: "diagram" | "chart" | "photo" | "screenshot" | "code" | "other";
            /** Image Url */
            image_url: string;
            /** Caption */
            caption?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Unreadable Parts */
            unreadable_parts?: string | null;
            /** Page Label */
            page_label?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamDeckEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSummary"][];
                };
            };
        };
    };
    createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createDeck"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorderImageSlides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSlides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slide"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSlide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slide"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setSlideHint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HintIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slide"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEstimate: {
        parameters: {
            query: {
                stage: "research" | "process_sources" | "generate";
                /** @description comma-separated */
                formats?: string | null;
            };
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEstimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startResearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDeckSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addDeckSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_addDeckSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateDeckSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approveSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDisagreements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disagreement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationDocument"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                format: "pdf" | "docx" | "md" | "html";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    askQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionIn"];
            };
        };
        responses: {
            /** @description SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getQaThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answerQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revealQuizAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
